### PR TITLE
Bump core-text and core-foundation versions

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by MSleepyPanda** [comment]
Please do a (semver-) minor version bump to reflect the dependency changes.

Looks fine otherwise. Mac builds seem to have gotten more rare on travis in the last time.

**Comment by glennw** [comment]
Oops! Fixed.

**Comment by MSleepyPanda** [comment]
Thanks!

**Comment by glennw** [comment]
No worries! Would you be able to publish this new version on crates.io when you have a moment? Thanks.

**Pull request merged**
