### PR TITLE
Bump text

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by MSleepyPanda** [comment]
Please ignore travis for now, setup is broken. Reintroduce the version bump and then i'm down for it

**Comment by Eijebong** [comment]
It's probably not good anyway... I don't have a mac to test it (kinda hoped travis would help there).

**Comment by MSleepyPanda** [comment]
Well me neither. Public api [changed since then](https://github.com/servo/core-text-rs/commit/2e97ea2d63ee20aa4356fd69ab6bc20c5aeb4334), but our impl should remain untouched. Though i'd like someone to confirm it building on mac.
This and the minor version bump. Then i'm ok with merging

**Comment by killercup** [comment]
```bash
rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-apple-darwin
release: 1.18.0
LLVM version: 3.9
```

**Comment by Eijebong** [comment]
Nooo don't merge it :o There was still a WIP commit in :/

**Comment by MSleepyPanda** [comment]
Well seems fine for me? @Eijebong 
What needs to be done?

**Comment by Eijebong** [comment]
Should've waited for me to remove the WIP commit ^^ I'll send another PR to bump the version when servo people are ready to bump everything at once :)

**Comment by MSleepyPanda** [comment]
Well did the bump on my own :D we're five minutes in, if you prefer, i'll just rebase on https://github.com/MSleepyPanda/rust-font-loader/pull/8/commits/f862919354bd8763291f3a88a33db0806079d59e ? :) @Eijebong

**Comment by Eijebong** [comment]
Nah, I guess that's ok

**Comment by MSleepyPanda** [comment]
If you want to, please open another PR with version bumps.  Don't want to steal your credit @Eijebong :)

**Comment by Eijebong** [comment]
It's not about credit ^^ It's about not breaking servo

**Pull request merged**
